### ISSUE TITLE
created a simple-prompt

### ISSUE THREAD

**Issue by zettlrobert** [zap-zsh/outlet#3]
just wanted to let you know that i created a simple prompt, feel free to add it to the readme.

```
- [simple-prompt](https://github.com/zettlrobert/simple-prompt) - A simple, minimal two line zsh prompt
```
Overall I am happy with how it turned out for my first zsh-prompt.

## Goals for Prompt(for now)
- output empty line after `stdout` to have clear separation before next prompt
 - find a way to not do that for the first prompt or after clear, they should be at the very top

**Comment by mamaraddio** [comment]
Merged

**Comment by zettlrobert** [comment]
thnaks!
